#include <fujinet-int.h>
#include <fujinet-commands.h>

#define CLK_CMD_SIMPLE_BINARY          APETIMECMD_SETTZ_ALT2
#define CLK_CMD_PRODOS_BINARY          APETIMECMD_GET_PRODOS
#define CLK_CMD_APETIME_BINARY         APETIMECMD_GET_ATARI
#define CLK_CMD_TZ_ISO_STRING          APETIMECMD_GET_ISO_LOCAL
#define CLK_CMD_UTC_ISO_STRING         APETIMECMD_GET_ISO_UTC
#define CLK_CMD_APPLE3_SOS_BINARY      APETIMECMD_GET_SOS


static const uint8_t _clk_cmd[] = {
  CLK_CMD_SIMPLE_BINARY,
  CLK_CMD_PRODOS_BINARY,
  CLK_CMD_APETIME_BINARY,
  CLK_CMD_TZ_ISO_STRING,
  CLK_CMD_UTC_ISO_STRING,
  CLK_CMD_APPLE3_SOS_BINARY
};

const uint8_t *clk_cmd     = _clk_cmd;